routes/web.php
<?php

use App\Http\Controllers\CasOngController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UrlsCasController;
use App\Http\Controllers\UrlsCategoryController;
use App\Http\Controllers\UrlsRetourCasController;
use App\Http\Controllers\DonController;
use App\Http\Controllers\UserphoneControllerWeb;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});
//route home

// Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//routes utilisateurs

Route::resource('users', UserController::class);

Route::PUT('users/statut/{user}', [UserController::class, 'statut'])->name('users.statut');

Auth::routes(['verify' => true]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::delete('users/force/{user}', [UserController::class, 'forceDestroy'])->name('users.force.destroy');

Route::put('users/restore/{user}', [UserController::class, 'restore'])->name('users.restore');

Route::get('profil/{user}', [App\Http\Controllers\ProfilController::class, 'show'])->name('profil');

Route::get('profil/{user}/edit', [App\Http\Controllers\ProfilController::class, 'edit'])->name('profil.edit')->middleware('nondemandeur');
Route::put('profil/{user}/edit', [App\Http\Controllers\ProfilController::class, 'update'])->name('profil.update')->middleware('nondemandeur');

Route::get('profil/{user}/editImage', [App\Http\Controllers\ProfilController::class, 'editImage'])->name('profil.editImage');
Route::put('profil/{user}/editImage', [App\Http\Controllers\ProfilController::class, 'updateImage'])->name('profil.updateImage');

Route::get('profil/{user}/editPassword', [App\Http\Controllers\ProfilController::class, 'editPassword'])->name('profil.editPassword')->middleware('password.confirm');;
Route::put('profil/{user}/editPassword', [App\Http\Controllers\ProfilController::class, 'updatePassword'])->name('profil.updatePassword');

//routes cas

Route::resource('cas', UrlsCasController::class)->middleware('admin');


Route::PUT('cas/statut/{cas}', [UrlsCasController::class, 'statut'])->name('cas.statut')->middleware('admin');

Route::delete('cas/force/{cas}', [UrlsCasController::class, 'forceDestroy'])->name('cas.forceDestroy')->middleware('admin');

Route::put('cas/restore/{cas}', [UrlsCasController::class, 'restore'])->name('cas.restore')->middleware('admin');

//routes cas ONG

Route::resource('Mescas', CasOngController::class)->middleware('nonadmin');

//routes catégories

Route::resource('categories', UrlsCategoryController::class)->middleware('admin');

//routes RetourCas

Route::resource('retour_cas', UrlsRetourCasController::class)->middleware('auth');

Route::get('MesRetoursCas', [App\Http\Controllers\UrlsRetourCasController::class, 'indexONG'])->name('indexONG')->middleware('nonadmin');
Route::get('RetoursCas', [App\Http\Controllers\UrlsRetourCasController::class, 'create'])->name('retour_cas.create')->middleware('nonadmin');
Route::post('RetoursCas', [App\Http\Controllers\UrlsRetourCasController::class, 'store'])->name('retour_cas.store')->middleware('nonadmin');

Route::PUT('retour_cas/statut/{retour_cas}', [UrlsRetourCasController::class, 'statut'])->name('retour_cas.statut')->middleware('admin');

Route::delete('retour_cas/force/{retour_cas}', [UrlsRetourCasController::class, 'forceDestroy'])->name('retour_cas.forceDestroy')->middleware('admin');

Route::put('retour_cas/restore/{retour_cas}', [UrlsRetourCasController::class, 'restore'])->name('retour_cas.restore')->middleware('admin');

//routes Dons

Route::resource('dons', DonController::class)->middleware('auth');

//routes userphones

Route::resource('userphones', UserphoneControllerWeb::class )->middleware('admin');
Route::put('userphones/restore/{userphone}', [UserphoneControllerWeb::class, 'restore'])->name('userphones.restore');

app/Models/Userphone.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Passport\HasApiTokens;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;

class Userphone extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens,Notifiable, HasFactory, SoftDeletes;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nom',
        'prenom',
        'email',
        'password',
        'telephone',
        'photo',
        'genre'
    ];


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function dons()
    { 
        return $this->hasMany(Don::class); 
    }
}

app/Http/Controllers/UserphoneController.php
<?php

namespace App\Http\Controllers;
use App\Models\Userphone;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;


class UserphoneController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    // public function index()
    // {
    //     return Userphone::withTrashed()->oldest('id')->get();
    // }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    // public function store(Request $request)
    // {
    //     Userphone::create($request->all());
    //     $request->validate([
    //         'nom' => ['required', 'string','max:25'],
    //         'prenom' => ['required', 'string','max:100'],
    //         'telephone' => ['required', 'numeric'],
    //         'genre' => ['required', 'string'],
    //         'photo' => '|image|mimes:jpg,png,jpeg,gif,svg|max:4000',
    //         'password' => ['required','min:8','max:100','string'],
    //         'password_confirm' => ['required','same:password'],
    //         'email' => ['required', 'email'],
    //     ]);
        
    //     $userphone = new Userphone;
    //     if($request->hasFile('photo')){
    //         $request->validate([
    //             'photo' => '|image|mimes:jpg,png,jpeg,gif,svg|max:4000',
    //         ]);
    //         $path = $request->file('photo')->store('public/images');
    //         $userphone->photo = $path;
    //     }else 
    //     {
    //         $path = ('public/images/user.png');
    //         $userphone->photo = $path;
    //     }
                       
    //     $userphone->nom = $request->nom;
    //     $userphone->prenom = $request->prenom;
    //     $userphone->email = $request->email;
    //     $userphone->genre = $request->genre;
    //     $userphone->telephone = $request->telephone;
    //     $userphone->password = Hash::make($request->password);
    //     $userphone->save();
    // }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Userphone  $userphone
     * @return \Illuminate\Http\Response
     */
    public function show(Userphone $userphone)
    {   
        return $userphone;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Userphone  $userphone
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {   
        $userphone = Userphone::find($id);
        $request->validate([
            'nom' => ['required', 'string','max:25'],
            'genre' => ['required', 'string'],
            'prenom' => ['required', 'string','max:100'],           
            'telephone' => ['required', 'numeric'],
            'email' => ['required', 'email'],
            'photo' => '|image|mimes:jpg,png,jpeg,gif,svg|max:4000',
        ]);
        $userphone->update($request->toArray());
        if($request->hasFile('photo')){
            $request->validate([
                'photo' => '|image|mimes:jpg,png,jpeg,gif,svg|max:4000',
            ]);
            $path = $request->file('photo')->store('public/images');
            $userphone->photo = $path;
        }else 
        {
            $path = ('public/images/user.png');
            $userphone->photo = $path;
        }
        return response()->json($userphone);
    }
    public function UpdateImage(Request $request, $id)
    {           
        $userphone = Userphone::find($id);
        $request->validate([
            'photo' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:5000',
        ]);
        if($request->hasFile('photo')){
            $request->validate([
              'photo' => '|image|mimes:jpg,png,jpeg,gif,svg|max:5000',
            ]);
            $path = $request->file('photo')->store('public/images');
            $userphone->photo = $path;
        }else 
        {       
            $path = ('public/images/user.png');
            $userphone->photo = $path;
        }
        $userphone->save();
        $response = ['message' => 'You have been added picture!'];
        return response($response, 200);
    }
    public function updatePassword(Request $request, $id)
    {           
        $request->validate([
            'password' => ['required','min:8','max:100','string'],
            'password_confirmation' => ['required','same:password'],
        ]);
        $userphone = Userphone::find($id);
             $userphone->password = Hash::make($request->password);
             $userphone->save();  
             $response = ['message' => 'You have been updated your password!'];
        return response($response, 200); 
             
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Userphone  $userphone
     * @return \Illuminate\Http\Response
     */
    public function destroy(Userphone $userphone)
    {
       $userphone->delete();
       $response = ['message' => 'You have been deleted!'];
        return response($response, 200);
    }
}

resources/views/userphones/index.blade.php
@extends('../layout/body')
@section('contenu')
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif
    <div class="card shadow mb-4">         
        <div class="card-body">  
        <div class="table-responsive">
            <table id="leTab" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>N°</th>
                        <th>NOM</th>
                        <th>PRENOM</th>
                        <th>TELEPHONE</th>
                        <th>E-MAIL</th>
                        <th>ACTIONS</th>
                        
                    </tr> 
                </thead>
                <tbody>
                    <?php $i=1 ;?>
                    @foreach ($userphones as $userphone)               
                    <tr>
                        <td>{{ $i++ }}</td>
                        <td>{{ $userphone->nom }}</td>
                        <td>{{ $userphone->prenom }}</td>
                        <td>{{ $userphone->telephone }}</td>
                        <td>{{ $userphone->email }}</td>
                        <td style="text-align: center;">
                            @if (! $userphone->deleted_at)
                            <form action="{{ route('userphones.destroy', $userphone->id) }}" method="post">
                                @csrf
                                @method('DELETE')
                                <a title="voir plus" class="btn btn-info btn-xs" href="{{ route('userphones.show', $userphone->id) }}"><i style="width:10px;float:left;" class="fa fa-plus"></i></a>              
                                <button class="btn btn-danger  btn-xs" onclick="return confirm('Voulez vous vraiment Suspendre cet utilisateur ?');" title="Suspendre"  ><i style="width:10px; float:right;"  class="fas fa-toggle-off"></i></button>
                            </form>
                            @else
                                <form action="{{ route('userphones.restore', $userphone->id) }}" method="post">
                                    @csrf
                                    @method('PUT')
                                    <button class="btn btn-warning btn-xs" title="Restaurer"><i title="restaurer" style="" class="fa fa-undo"></i></button>
                                </form>
                            @endif
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        </div>
    </div>

@endsection

resources/views/userphones/show.blade.php
@extends('../layout/body')
@section('contenu')
    <div class="container">
        <div align="center">  
            <a href="{{route('userphones.index') }}" class="btn btn-primary" align="center"><i class="fas fa-phone"></i>&nbspListe des Utilisateurs Mobile</a>         
        </div>
        <section class="ftco-counter img ftco-section ftco-no-pt ftco-no-pb" id="about-section">
            <div class="container">
                <div class="row d-flex">
                    <div class="col-md-6 col-lg-5 d-flex">
                        <div style="width: 300px; height: 350px;margin-top: 100px;" class="img d-flex align-self-stretch align-items-center">
                            <img style="width: 100%; height: 100%;" src="{{ Storage::url($userphone->photo) }}" class="img-thumbnail" alt="...">
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-7 pl-lg-5">
                        <div>
                            <div class="row justify-content-start pb-3">
                                <div class="col-md-12 heading-section ftco-animate p-4 p-lg-5">
                                    <h4 class="mb-4">Id : {{ $userphone->id }} </h2>
                                    <h4 class="mb-4">Nom : {{ $userphone->nom }} </h2> 
                                    <h4 class="mb-4">Prenom : {{ $userphone->prenom }} </h2>
                                    <h4 class="mb-4">Telephone : {{ $userphone->telephone }} </h2>
                                    <h4 class="mb-4">Adresse e-mail : {{ $userphone->email }} </h2>
                                    <h4 class="mb-4">Genre : {{ $userphone->genre }} </h2>
                                    <h4 class="mb-4">Inscrit le : {{ $userphone->created_at }} </h2>                      
                                </div>
                        </div>
                    </div>
                </div>
                   
                </div>
            </div>
           
        </section>

    </div>
@endsection