routes/web.php
<?php

use App\Http\Controllers\CasOngController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UrlsCasController;
use App\Http\Controllers\UrlsCategoryController;
use App\Http\Controllers\UrlsRetourCasController;
use App\Http\Controllers\DonController;
use App\Http\Controllers\UserphoneControllerWeb;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});
//route home

// Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//routes utilisateurs

Route::resource('users', UserController::class);

Route::PUT('users/statut/{user}', [UserController::class, 'statut'])->name('users.statut');

Auth::routes(['verify' => true]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::delete('users/force/{user}', [UserController::class, 'forceDestroy'])->name('users.force.destroy');

Route::put('users/restore/{user}', [UserController::class, 'restore'])->name('users.restore');

Route::get('profil/{user}', [App\Http\Controllers\ProfilController::class, 'show'])->name('profil');

Route::get('profil/{user}/edit', [App\Http\Controllers\ProfilController::class, 'edit'])->name('profil.edit')->middleware('nondemandeur');
Route::put('profil/{user}/edit', [App\Http\Controllers\ProfilController::class, 'update'])->name('profil.update')->middleware('nondemandeur');

Route::get('profil/{user}/editImage', [App\Http\Controllers\ProfilController::class, 'editImage'])->name('profil.editImage');
Route::put('profil/{user}/editImage', [App\Http\Controllers\ProfilController::class, 'updateImage'])->name('profil.updateImage');

Route::get('profil/{user}/editPassword', [App\Http\Controllers\ProfilController::class, 'editPassword'])->name('profil.editPassword')->middleware('password.confirm');;
Route::put('profil/{user}/editPassword', [App\Http\Controllers\ProfilController::class, 'updatePassword'])->name('profil.updatePassword');

//routes cas

Route::resource('cas', UrlsCasController::class)->middleware('admin');


Route::PUT('cas/statut/{cas}', [UrlsCasController::class, 'statut'])->name('cas.statut')->middleware('admin');

Route::delete('cas/force/{cas}', [UrlsCasController::class, 'forceDestroy'])->name('cas.forceDestroy')->middleware('admin');

Route::put('cas/restore/{cas}', [UrlsCasController::class, 'restore'])->name('cas.restore')->middleware('admin');

//routes cas ONG

Route::resource('Mescas', CasOngController::class)->middleware('nonadmin');

//routes catégories

Route::resource('categories', UrlsCategoryController::class)->middleware('admin');

//routes RetourCas

Route::resource('retour_cas', UrlsRetourCasController::class)->middleware('auth');

Route::get('MesRetoursCas', [App\Http\Controllers\UrlsRetourCasController::class, 'indexONG'])->name('indexONG')->middleware('nonadmin');
Route::get('RetoursCas', [App\Http\Controllers\UrlsRetourCasController::class, 'create'])->name('retour_cas.create')->middleware('nonadmin');
Route::post('RetoursCas', [App\Http\Controllers\UrlsRetourCasController::class, 'store'])->name('retour_cas.store')->middleware('nonadmin');

Route::PUT('retour_cas/statut/{retour_cas}', [UrlsRetourCasController::class, 'statut'])->name('retour_cas.statut')->middleware('admin');

Route::delete('retour_cas/force/{retour_cas}', [UrlsRetourCasController::class, 'forceDestroy'])->name('retour_cas.forceDestroy')->middleware('admin');

Route::put('retour_cas/restore/{retour_cas}', [UrlsRetourCasController::class, 'restore'])->name('retour_cas.restore')->middleware('admin');

//routes Dons

Route::resource('dons', DonController::class)->middleware('auth');

//routes userphones

Route::resource('userphones', UserphoneControllerWeb::class )->middleware('admin');
Route::put('userphones/restore/{userphone}', [UserphoneControllerWeb::class, 'restore'])->name('userphones.restore');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $table = "categories";

    protected $fillable = ['nom', 'autre'];

    //relation entre catégories et cas
    public function cas() 
    { 
        return $this->hasMany(Cas::class); 
    }
}

resources/views/categories/create.blade.php
@extends('layout/body')
@section('contenu')

    <div class="container mt-2">
    
    <div class="row">
        <div class="col-lg-8 margin-tb">
            <div class="pull-left mb-2">
                <h2 style="margin-left: 20px;">Ajouter une catégorie</h2>
            </div>
        </div>
    </div><br>
    
    @if(session('status'))
        <div class="alert alert-success mb-1 mt-1">
            {{ session('status') }}
        </div>
    @endif
   
    <form action="{{ route('categories.store') }}" method="POST" >
        @csrf

        <div class="row" >
            <div class="col-xs-8 col-sm-8 col-md-8"  style="margin-left:15px;">
                <div class="form-group">
                    <strong>Nom de la catégorie:</strong>
                    <input type="text" name="nom" class="form-control" placeholder="Nom de la catégories">
                    @error('nom')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                    @enderror
                </div>
                <a class="btn btn-secondary" href="{{ route('categories.index') }}" style="margin-left:15px;"> Annuler</a>
                <button type="submit" class="btn btn-primary ml-3">Envoyer</button>
            </div>
        </div>
    </form>
@endsection

resources/views/categories/edit.blade.php
@extends('layout/body')
@section('contenu')


<div class="container mt-2">
    <div class="row">
        <div class="col-lg-8 margin-tb">
            <div class="pull-left">
                <h2 style="margin-left: -15px;" >Modifier une catégorie </h2>
            </div>
    </div><br>
   
  @if(session('status'))
    <div class="alert alert-success mb-1 mt-1">
        {{ session('status') }}
    </div>
  @endif

    <form action="{{ route('categories.update', $categories->id) }}" method="POST" style="margin-left: 20px;">
        @csrf
        @method('PUT')
   
        <div class="row">
            <div class="col-xs-8 col-sm-8 col-md-8">
                <div class="form-group">
                    <strong>Nom de la catégorie:</strong>
                    <input type="text" name="titre" value="{{ old('nom', $categories->nom) }}" class="form-control" placeholder="Titre du cas">
                    @error('titre')
                     <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div>
                <a class="btn btn-secondary" href="{{ route('categories.index') }}" enctype="multipart/form-data" style="margin-left: 15px;">Annuler</a>
                <input type="submit" class="btn btn-primary ml-3" value="Enregistrer">
            </div>
        </div>
    </form>
</div>

@endsection

resources/views/categories/index.blade.php
@extends('layout/body')
@section('contenu')
    <style>
        th{
            text-align: center;
        }
        td{
            text-align: center;
        }
    </style>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 margin-tb">
               <div class="pull-right mb-2" style="float: right;">
                    <a class="btn btn-primary" href="{{ route('categories.create') }}"><span class=pull-right>Ajouter une catégorie</span></a>
              </div>
           </div>
    </div>
       @if ($message = Session::get('success'))
         <div class="alert alert-success">
            <p>{{ $message }}</p>
         </div>
        @endif
    <div class="table-responsive">
        <table class="table table-striped table-bordered" id="TabCategories" style="width:100%">
            <thead> 
                <tr>
                    <th>N°</th>
                    <th>Nom</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($categories as $categories)
                    <tr>
                        <td>{{ $categories->id }}</td>
                        <td>{{ $categories->nom }}</td>
                        <td>
                            <form action="{{ route('categories.destroy', $categories->id) }}" method="POST" style="display:inline;">
            
                                @csrf
                                @method('DELETE')

                                <a class="btn btn-primary" title="Modifier" href="{{ route('categories.edit', $categories->id) }}" style="display:inline;"><i class="fas fa-pen"></i></a>
                                <button title="Supprimer" title="Supprimer" type="submit" class="btn btn-danger" onclick="return confirm('Voulez vous vraiment Supprimer cette catégorie ?');" ><i class="fa fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>            
        </table>
    </div>
</div>
</html>
@endsection