routes/web.php
<?php

use App\Http\Controllers\CasOngController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UrlsCasController;
use App\Http\Controllers\UrlsCategoryController;
use App\Http\Controllers\UrlsRetourCasController;
use App\Http\Controllers\DonController;
use App\Http\Controllers\UserphoneControllerWeb;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});
//route home

// Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//routes utilisateurs

Route::resource('users', UserController::class);

Route::PUT('users/statut/{user}', [UserController::class, 'statut'])->name('users.statut');

Auth::routes(['verify' => true]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::delete('users/force/{user}', [UserController::class, 'forceDestroy'])->name('users.force.destroy');

Route::put('users/restore/{user}', [UserController::class, 'restore'])->name('users.restore');

Route::get('profil/{user}', [App\Http\Controllers\ProfilController::class, 'show'])->name('profil');

Route::get('profil/{user}/edit', [App\Http\Controllers\ProfilController::class, 'edit'])->name('profil.edit')->middleware('nondemandeur');
Route::put('profil/{user}/edit', [App\Http\Controllers\ProfilController::class, 'update'])->name('profil.update')->middleware('nondemandeur');

Route::get('profil/{user}/editImage', [App\Http\Controllers\ProfilController::class, 'editImage'])->name('profil.editImage');
Route::put('profil/{user}/editImage', [App\Http\Controllers\ProfilController::class, 'updateImage'])->name('profil.updateImage');

Route::get('profil/{user}/editPassword', [App\Http\Controllers\ProfilController::class, 'editPassword'])->name('profil.editPassword')->middleware('password.confirm');;
Route::put('profil/{user}/editPassword', [App\Http\Controllers\ProfilController::class, 'updatePassword'])->name('profil.updatePassword');

//routes cas

Route::resource('cas', UrlsCasController::class)->middleware('admin');


Route::PUT('cas/statut/{cas}', [UrlsCasController::class, 'statut'])->name('cas.statut')->middleware('admin');

Route::delete('cas/force/{cas}', [UrlsCasController::class, 'forceDestroy'])->name('cas.forceDestroy')->middleware('admin');

Route::put('cas/restore/{cas}', [UrlsCasController::class, 'restore'])->name('cas.restore')->middleware('admin');

//routes cas ONG

Route::resource('Mescas', CasOngController::class)->middleware('nonadmin');

//routes catégories

Route::resource('categories', UrlsCategoryController::class)->middleware('admin');

//routes RetourCas

Route::resource('retour_cas', UrlsRetourCasController::class)->middleware('auth');

Route::get('MesRetoursCas', [App\Http\Controllers\UrlsRetourCasController::class, 'indexONG'])->name('indexONG')->middleware('nonadmin');
Route::get('RetoursCas', [App\Http\Controllers\UrlsRetourCasController::class, 'create'])->name('retour_cas.create')->middleware('nonadmin');
Route::post('RetoursCas', [App\Http\Controllers\UrlsRetourCasController::class, 'store'])->name('retour_cas.store')->middleware('nonadmin');

Route::PUT('retour_cas/statut/{retour_cas}', [UrlsRetourCasController::class, 'statut'])->name('retour_cas.statut')->middleware('admin');

Route::delete('retour_cas/force/{retour_cas}', [UrlsRetourCasController::class, 'forceDestroy'])->name('retour_cas.forceDestroy')->middleware('admin');

Route::put('retour_cas/restore/{retour_cas}', [UrlsRetourCasController::class, 'restore'])->name('retour_cas.restore')->middleware('admin');

//routes Dons

Route::resource('dons', DonController::class)->middleware('auth');

//routes userphones

Route::resource('userphones', UserphoneControllerWeb::class )->middleware('admin');
Route::put('userphones/restore/{userphone}', [UserphoneControllerWeb::class, 'restore'])->name('userphones.restore');

app/Http/Controllers/CasOngController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cas;
use App\Models\Category;
use Illuminate\Http\Request;

class CasOngController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['cas'] =Cas::where([
            ['users_id', auth()->user()->id],
            ])->get();
        return view('casONG.indexCas', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('cas.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'titre' => 'required',
            'image1' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:10000',
            'image2' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:10000',
            'image3' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:10000',
            'image4' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:10000',
            'description' => 'required',
            'ville' => 'required|string|max:30',
            'quartier' => 'required|string|max:30',
            'numero' => 'required|min:9',
            'montant' => 'required',
        ]);
        $image1 = $request->file('image1')->getClientOriginalName();
        $image2 = $request->file('image2')->getClientOriginalName();
        $image3 = $request->file('image3')->getClientOriginalName();
        $image4 = $request->file('image4')->getClientOriginalName();

        $request->file('image1')->storeAs('public/Image_Cas', $image1);
        $request->file('image2')->storeAs('public/Image_Cas', $image2);
        $request->file('image3')->storeAs('public/Image_Cas', $image3);
        $request->file('image4')->storeAs('public/Image_Cas', $image4);

        $cas = new Cas;
        $cas->titre = $request->titre;
        $cas->categories_id = $request->categories_id;
        $cas->description = $request->description;
        $cas->image1 = $image1;
        $cas->image2 = $image2;
        $cas->image3 = $image3;
        $cas->image4 = $image4;
        $cas->ville = $request->ville;
        $cas->quartier = $request->quartier;
        $cas->numero = $request->numero;
        $cas->montant = $request->montant;
        $cas->users_id = auth()->user()->id;
        $cas->save();
            
        
        return redirect()->route('Mescas.index')
                        ->with('success','Cas enregistrer avec succès.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Cas  $cas
     * @return \Illuminate\Http\Response
     */
    public function show(Cas $cas, $id)
    {
        $cas = Cas::findOrFail($id);

        //recuperation du nom de la catégorie
        $categories = $cas->categories->nom;  

        //recuperation des infos de l'utilisateur
        $users = $cas->users->photo;
        $users = $cas->users->nom;
        $users = $cas->users->prenom; 

        return view('cas.show',compact('cas', 'categories'));
    } 

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Cas  $cas
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cas = Cas::findOrFail($id);

        $categories = Category::all();

        if($cas->statut==1){
            return redirect()->route('Mescas.index')
                            ->with('success', 'Impossible de modifier un cas déjà publié');
        }


        return view('cas.edit',compact('cas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Cas  $cas
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'titre' => 'required',
            'image1' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:10000',
            'image2' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:10000',
            'image3' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:10000',
            'image4' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:10000',
            'description' => 'required',
            'ville' => 'required|string|max:30',
            'quartier' => 'required|string|max:30',
            'numero' => 'required|min:9',
            'montant' => 'required',
        ]);
        
        $image1 = $request->file('image1')->getClientOriginalName();
        $image2 = $request->file('image2')->getClientOriginalName();
        $image3 = $request->file('image3')->getClientOriginalName();
        $image4 = $request->file('image4')->getClientOriginalName();

        $cas = Cas::find($id);
        if($request->hasFile('image1', 'image2', 'image3', 'image4')){
            $request->validate([
                'image1' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:10000',
                'image2' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:10000',
                'image3' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:10000',
                'image4' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:10000',
            ]);
            $request->file('image1')->storeAs('public/Image_Cas', $image1);
            $request->file('image2')->storeAs('public/Image_Cas', $image2);
            $request->file('image3')->storeAs('public/Image_Cas', $image3);
            $request->file('image4')->storeAs('public/Image_Cas', $image4 );
            $cas->image1 = $image1;
            $cas->image2 = $image2;
            $cas->image3 = $image3;
            $cas->image4 = $image4;

        }
        $cas->titre = $request->titre;
        $cas->description = $request->description;
        $cas->image1 = $image1;
        $cas->image2 = $image2;
        $cas->image3 = $image3;
        $cas->image4 = $image4;
        $cas->ville = $request->ville;
        $cas->quartier = $request->quartier;
        $cas->numero = $request->numero;
        $cas->montant = $request->montant;
        $cas->users_id = auth()->user()->id;
        $cas->save();
        return redirect()->route('Mescas.index')
                        ->with('success','Cas modifier avec succès');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Cas  $cas
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cas = Cas::findOrFail($id);

        $cas->delete();
    
        return redirect()->route('cas.index')
                        ->with('success','Cas supprimer avec succès');
    }
}

resources/views/casONG/indexCas.blade.php
@extends('layout/body')
@section('contenu')
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif
    <style>
        th{
            text-align: center;
        }
    </style>
   
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-right mb-2" style="float: right;">
                        <a class="btn btn-primary"  href="{{ route('Mescas.create') }}"> <span class=pull-right> Créer un nouveau cas</span></a>
                </div>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-bordered" id="TabCas" style="width:100%">
                <thead> 
                    <tr>
                        <th>N°</th>
                        <th>Titre</th>
                        <th>Numéro</th>
                        <th>Montant</th>
                        <th>Status</th>
                        <th>Actions</th>
                        <th>Retour du Cas</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($cas as $cas)
                        <tr>
                            <td>{{ $cas->id }}</td>
                            <td>{{ $cas->titre }}</td>
                            <td>{{ $cas->numero }}</td>
                            <td>{{ $cas->montant }} GNF</td> 
                            <td style="text-align: center"> 

                                <form action="{{ route('cas.statut', $cas->id) }}" method = "POST">
                                    @csrf
                                    @method('PUT')

                                    @if($cas->statut)
                                        Publié
                                    @else
                                        Publication en attente
                                    @endif
                                </form>
                            </td>
                            <td style="text-align: center;">
                                <form action="{{ route('cas.edit',$cas->id) }}" method="POST" style="display:inline;">

                                    @csrf
                                    @method('DELETE')

                                    @if($cas->statut)       
                                        <a class="btn btn-warning btn-xs" title="Voir plus" href="{{ route('Mescas.show', $cas->id) }}" ><i style="width:10px;float:left;" class="fa fa-eye"></i></a>                                 
                                    @else
                                        <a class="btn btn-warning btn-xs" title="Voir plus" href="{{ route('Mescas.show', $cas->id) }}" ><i style="width:10px;float:left;" class="fa fa-eye"></i></a>
                                        <a class="btn btn-primary btn-xs" title="Modifier" href="{{ route('Mescas.edit', $cas->id) }}"><i style="width:10px;float:left;" class="fa fa-pen"></i></a>
                                    @endif
                                </form>
                            </td>
                            <td>
                            @if($cas->statut)                           
                            <a class="btn btn-primary" href="{{ route('retour_cas.create') }}">Faire un retour</a>
                            @else
                            Cas Suspendu
                            @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</html>
@endsection