routes/web.php
<?php

use App\Http\Controllers\CasOngController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UrlsCasController;
use App\Http\Controllers\UrlsCategoryController;
use App\Http\Controllers\UrlsRetourCasController;
use App\Http\Controllers\DonController;
use App\Http\Controllers\UserphoneControllerWeb;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});
//route home

// Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//routes utilisateurs

Route::resource('users', UserController::class);

Route::PUT('users/statut/{user}', [UserController::class, 'statut'])->name('users.statut');

Auth::routes(['verify' => true]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::delete('users/force/{user}', [UserController::class, 'forceDestroy'])->name('users.force.destroy');

Route::put('users/restore/{user}', [UserController::class, 'restore'])->name('users.restore');

Route::get('profil/{user}', [App\Http\Controllers\ProfilController::class, 'show'])->name('profil');

Route::get('profil/{user}/edit', [App\Http\Controllers\ProfilController::class, 'edit'])->name('profil.edit')->middleware('nondemandeur');
Route::put('profil/{user}/edit', [App\Http\Controllers\ProfilController::class, 'update'])->name('profil.update')->middleware('nondemandeur');

Route::get('profil/{user}/editImage', [App\Http\Controllers\ProfilController::class, 'editImage'])->name('profil.editImage');
Route::put('profil/{user}/editImage', [App\Http\Controllers\ProfilController::class, 'updateImage'])->name('profil.updateImage');

Route::get('profil/{user}/editPassword', [App\Http\Controllers\ProfilController::class, 'editPassword'])->name('profil.editPassword')->middleware('password.confirm');;
Route::put('profil/{user}/editPassword', [App\Http\Controllers\ProfilController::class, 'updatePassword'])->name('profil.updatePassword');

//routes cas

Route::resource('cas', UrlsCasController::class)->middleware('admin');


Route::PUT('cas/statut/{cas}', [UrlsCasController::class, 'statut'])->name('cas.statut')->middleware('admin');

Route::delete('cas/force/{cas}', [UrlsCasController::class, 'forceDestroy'])->name('cas.forceDestroy')->middleware('admin');

Route::put('cas/restore/{cas}', [UrlsCasController::class, 'restore'])->name('cas.restore')->middleware('admin');

//routes cas ONG

Route::resource('Mescas', CasOngController::class)->middleware('nonadmin');

//routes catégories

Route::resource('categories', UrlsCategoryController::class)->middleware('admin');

//routes RetourCas

Route::resource('retour_cas', UrlsRetourCasController::class)->middleware('auth');

Route::get('MesRetoursCas', [App\Http\Controllers\UrlsRetourCasController::class, 'indexONG'])->name('indexONG')->middleware('nonadmin');
Route::get('RetoursCas', [App\Http\Controllers\UrlsRetourCasController::class, 'create'])->name('retour_cas.create')->middleware('nonadmin');
Route::post('RetoursCas', [App\Http\Controllers\UrlsRetourCasController::class, 'store'])->name('retour_cas.store')->middleware('nonadmin');

Route::PUT('retour_cas/statut/{retour_cas}', [UrlsRetourCasController::class, 'statut'])->name('retour_cas.statut')->middleware('admin');

Route::delete('retour_cas/force/{retour_cas}', [UrlsRetourCasController::class, 'forceDestroy'])->name('retour_cas.forceDestroy')->middleware('admin');

Route::put('retour_cas/restore/{retour_cas}', [UrlsRetourCasController::class, 'restore'])->name('retour_cas.restore')->middleware('admin');

//routes Dons

Route::resource('dons', DonController::class)->middleware('auth');

//routes userphones

Route::resource('userphones', UserphoneControllerWeb::class )->middleware('admin');
Route::put('userphones/restore/{userphone}', [UserphoneControllerWeb::class, 'restore'])->name('userphones.restore');

app/Models/Cas.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Cas extends Model
{
    use HasFactory;

    use SoftDeletes;
    
    protected $table = "cas";
    
    protected $fillable = ['titre', 'categories_id', 'description', 'image1', 'image2', 'image3', 'image4', 'quartier', 'ville', 'numero',  'montant', 'status', 'users_id'];

    protected $dates = [ 'deleted_at' ];

    //relation entres le modèle users et le modèle cas
    public function users()
        { 
            return $this->belongsTo(User::class); 
        }
//relation entres le modèle catégories et le modèle cas
    public function categories()
    { 
        return $this->belongsTo(Category::class); 
    }
//relation entres le modèle RetourCas et le modèle cas
    public function retourcas()
        {
            return $this->hasOne(RetourCas::class);
        }
//relation entres le modèle dons et le modèle cas
    public function dons()
    { 
        return $this->hasMany(Don::class); 
    }   
}

resources/views/cas/create.blade.php
@extends('layout/body')
@section('contenu')

<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 bg-info rounded text-white">

            <h1 align="center";>Création d'un cas</h1><br>

            @if(session('status'))
                <div class="alert alert-success mb-1 mt-1">
                    {{ session('status') }}
                </div>
            @endif

            <form action="{{ route('Mescas.store') }}" method="POST" enctype="multipart/form-data">
                @csrf

                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <div class="form-group rounded">
                            <strong>Titre du cas :</strong>
                            <input type="text" name="titre" class="form-control item" value="{{ old('titre') }}" placeholder="Titre" >
                            @error('titre')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group rounded">
                            <label ><strong>Catégorie :</strong></label><br>
                            <select name="categories_id">
                                @foreach($categories as $categories)
                                    <option value="{{ $categories->id }}">{{ $categories->nom }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group rounded">
                            <strong>Description :</strong>
                            <textarea  class="form-control item" name="description" value="{{ old('description') }}" placeholder="Description">{{ old('description') }}</textarea>
                            @error('description')
                            <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group rounded">
                            <strong>Ville :</strong>
                            <input type="text" name="ville" class="form-control item" value="{{ old('ville') }}" placeholder="Ville" >
                            @error('ville')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group rounded">
                            <strong>Quartier :</strong>
                            <input type="text" name="quartier" class="form-control item" value="{{ old('quartier') }}" placeholder="Quartier" >
                            @error('titre')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group rounded">
                            <strong>Téléphone :</strong>
                            <input type="number" name="numero" class="form-control item" value="{{ old('numero') }}" placeholder="Numére de téléphone" >
                            @error('numero')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group rounded">
                            <strong>Montant :</strong>
                            <input type="number" name="montant" class="form-control item" value="{{ old('montant') }}" placeholder="Montant estimer pour le cas" >
                            @error('montant')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group rounded">
                            <strong>Image descriptive du cas:</strong>
                            <input type="file" name="image1" class="form-control item" placeholder="Image" value="{{ old('image1') }}">
                            @error('image1')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group rounded">
                            <strong>Image descriptive du cas:</strong>
                            <input type="file" name="image2" class="form-control item" placeholder="Image" value="{{ old('image2') }}">
                            @error('image2')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group rounded">
                            <strong>Image descriptive du cas:</strong>
                            <input type="file" name="image3" class="form-control item" placeholder="Image" value="{{ old('image3') }}">
                            @error('image3')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group rounded">
                            <strong>Image descriptive du cas:</strong>
                            <input type="file" name="image4" class="form-control item" placeholder="Image" value="{{ old('image4') }}">
                            @error('image4')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                            @enderror
                        </div>
                        <a class="btn btn-secondary" href="{{ route('Mescas.index') }}" enctype="multipart/form-data" style="margin-left:30px;"> Annuler</a>
                        <button type="submit" class="btn btn-success ml-3">Publier</button>
                        </div>
                    <div class="col-md-2"></div>
                </div>
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>
</div> 

@endsection

resources/views/cas/edit.blade.php
@extends('layout/body')
@section('contenu')

<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 bg-info rounded text-white">

            <h1 align="center";>Modification du cas {{$cas->titre}}</h1><br>

            @if(session('status'))
                <div class="alert alert-success mb-1 mt-1">
                    {{ session('status') }}
                </div>
            @endif

            <form action="{{ route('Mescas.update', $cas->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <div class="form-group rounded">
                            <strong>Titre du cas :</strong>
                            <input type="text" name="titre" class="form-control item" placeholder="Titre" value="{{ old('titre', $cas->titre) }}">
                            @error('titre')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group rounded">
                            <strong>Description :</strong>
                            <textarea class="form-control item" name="description" placeholder="Description">{{ old('description', $cas->description) }}</textarea>
                            @error('description')
                            <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                            @enderror
                        </div>
                        
                        <div class="form-group rounded">
                            <strong>Ville :</strong>
                            <input type="text" name="ville" class="form-control item" value="{{ old('ville', $cas->ville) }}" placeholder="Quartier" >
                            @error('ville')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group rounded">
                            <strong>Quartier :</strong>
                            <input type="text" name="quartier" class="form-control item" value="{{ old('quartier', $cas->quartier) }}" placeholder="Quartier" >
                            @error('quartier')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group rounded">
                            <strong>Téléphone :</strong>
                            <input type="number" name="numero" class="form-control item" value="{{ old('numero', $cas->numero) }}" placeholder="Numére de téléphone" >
                            @error('numero')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group rounded">
                            <strong>Montant :</strong>
                            <input type="number" name="montant" class="form-control item" value="{{ old('montant', $cas->montant) }}" placeholder="Montant estimer pour le cas" >
                            @error('montant')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group rounded">
                            <strong>Image descriptive du cas :</strong>
                            <input type="file" name="image1" class="form-control item" placeholder="Image" value="{{ old('image1', $cas->image1) }}">
                            @error('image1')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group rounded">
                            <strong>Image descriptive du cas :</strong>
                            <input type="file" name="image2" class="form-control item" placeholder="Image" value="{{ old('image2', $cas->image2) }}">
                            @error('image2')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group rounded">
                            <strong>Image descriptive du cas :</strong>
                            <input type="file" name="image3" class="form-control item" placeholder="Image" value="{{ old('image3', $cas->image3) }}">
                            @error('image3')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group rounded">
                            <strong>Image descriptive du cas :</strong>
                            <input type="file" name="image4" class="form-control item" placeholder="Image" value="{{ old('image4', $cas->image4) }}">
                            @error('image4')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                            @enderror
                        </div>
                        <a class="btn btn-secondary" href="{{ route('cas.index') }}" enctype="multipart/form-data" onclick="return confirm('Voulez vous vraiment annuler la modification ?');"> Annuler</a>
                        <input type="submit" class="btn btn-success ml-3" value="Enregistrer">
                        </div>
                    <div class="col-md-2"></div>
                </div>
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>
</div> 

@endsection

resources/views/cas/index.blade.php
@extends('layout/body')
@section('contenu')
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif
    <style>
        th{
            text-align: center;
        }
        td{
            text-align: center;
        }
    </style>
   
    <div class="container-fluid">
        <div class="row">
            {{-- <div class="col-lg-12 margin-tb">
                <div class="pull-right mb-2" style="float: right;">
                        <a class="btn btn-primary"  href="{{ route('cas.create') }}"> <span class=pull-right> Créer un nouveau cas</span></a>
                </div>
            </div> --}}
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-bordered" id="TabCas" style="width:100%">
                <thead> 
                    <tr>
                        <th>N°</th>
                        <th>Titre</th>
                        <th>Numéro</th>
                        <th>Montant</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($cas as $cas)
                        <tr>
                            <td>{{ $cas->id }}</td>
                            <td>{{ $cas->titre }}</td>
                            <td>{{ $cas->numero }}</td>
                            <td>{{ $cas->montant }} GNF</td> 
                            <td style="text-align: center"> 
                            @if($cas->deleted_at)
                            <p style="text-align: center;">Cas Supprimer</p>
                            @else

                                <form action="{{ route('cas.statut', $cas->id) }}" method = "POST">
                                    @csrf
                                    @method('PUT')

                                    @if($cas->statut)
                                        <button type="submit" title="Suspendre" style="width:100%; float:left;" class="btn btn-danger btn-xs"><i style="" class="fa fa-ban"></i></button>
                                    @else
                                        <button type="submit" title="Valider" style="width:100%; float:left;" class="btn btn-success btn-xs"><i style="" class="fa fa-check"></i></button>
                                    @endif
                                </form>
                            @endif
                            </td>
                            <td style="text-align: center;">
                                <form action="{{ route('cas.edit',$cas->id) }}" method="POST" style="display:inline;">

                                    @csrf
                                    @method('DELETE')

                                    @if($cas->deleted_at)                                        
                                    @else
                                        <a class="btn btn-warning btn-xs" title="Voir plus" href="{{ route('cas.show', $cas->id) }}" ><i style="width:10px;float:left;" class="fa fa-eye"></i></a>
                                        {{-- <a class="btn btn-primary btn-xs" title="Modifier" href="{{ route('cas.edit', $cas->id) }}"><i style="width:10px;float:left;" class="fas fa-pen"></i></a> --}}
                                    @endif
                                </form>
                                <form action="{{ route($cas->deleted_at? 'cas.forceDestroy' : 'cas.destroy',$cas->id) }}" method="POST" style="display:inline;">
                
                                    @csrf
                                    @method('DELETE')

                                    <button  title="Supprimer" type="submit" class="btn btn-danger btn-xs" onclick="return confirm('Voulez vous vraiment Supprimer ce cas ?');" ><i style="width: 10px;" class="fa fa-trash"></i></button>
                                </form>
                                @if($cas->deleted_at)
                                    <form action="{{ route('cas.restore', $cas->id) }}" method="post" style="display:inline;">
                                        @csrf
                                        @method('PUT')
                                        <button title="Restaurer" class="btn btn-warning btn-xs" ><i class="fa fa-undo"></i></button>
                                    </form>
                                @endif
                            </td>
                            {{-- <td><a class="btn btn-primary" href="{{ route('retour_cas.create') }}">Faire un retour</a></td> --}}
                        </tr>
                    @endforeach
                </tbody>
                
            </table>
        </div>
    </div>
</html>
@endsection

resources/views/cas/show.blade.php
@extends('layout/body')
@section('contenu')


<div class="container-fluid">
	<div class="row">
		<div class="col-md-12" style="margin-left: 20px;">
			<div class="row">
				<div class="col-md-4" style="border:1px solid #C0C0C0;">
					<div class="row" style="text-aling: center;">
						<div class="col-md-4"></div>
						<div class="col-md-4">
							<img alt="Photo de l'utilisateur" src="{{ Storage::url($cas->users->photo) }}" alt="photo de profil" class="rounded-circle" style="width: 100%; padding-top: 10px;" />
						</div> 
						<div class="col-md-4"></div>
					</div><br>
                    <p style="text-aling: center;"><strong style="text-aling: center; margin-left: 20px;">Publier par: </strong>{{$cas->users->nom}} {{$cas->users->prenom}}</p>
                    <h2>Category : <a href=""><span class="theme_color">{{ $cas->categories->nom }}</span></a></h2>
					<div><h4><i class="icon-map-pin theme_color"></i><strong> Lieu du cas: </strong> {{$cas->ville}}, {{$cas->quartier}}</h4> </div>
                    <p><strong>Description :</strong></p>
                    <p>{{$cas->description}} </p>
                    <h5>Le montant estimer <br> pour le cas : <strong>{{$cas->montant}} GNF</strong></h5>
                    <h6>Faites un don sur ce numéro : <strong>{{$cas->numero}}</strong></h6><br>
				</div>
				<div class="col-md-8">
                    <div class="row" style="text-aling: center;">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <div  style="height: 50%;width: 80%;">
                            <h2 style="text-align: center;"><strong>{{$cas->titre}}</strong></h2> <br>
                            <div id="carousel" class="carousel slide" data-ride="carousel">
                                <ol class="carousel-indicators">
                                    <li data-target=".carousel" data-slide-to="0" class="active"></li>
                                    <li data-target=".carousel" data-slide-to="1"></li>
                                    <li data-target=".carousel" data-slide-to="2"></li>
                                    <li data-target=".carousel" data-slide-to="3"></li>
                                </ol>
                                <div class="carousel-inner">
                                    <div class="carousel-item active">
                                        <img class="d-block w-100" alt="Image descriptive" src="{{ asset('storage/Image_Cas/'. $cas->image1) }}" style="width: 100%; object-fit: cover;"/>
                                    </div>
                                    <div class="carousel-item">
                                        <img class="d-block w-100" alt="Image descriptive" src="{{ asset('storage/Image_Cas/'. $cas->image2) }}" style="width: 100%; object-fit: cover;"/>
                                    </div>
                                    <div class="carousel-item">
                                        <img class="d-block w-100" alt="Image descriptive" src="{{ asset('storage/Image_Cas/'. $cas->image3) }}" style="width: 100%; object-fit: cover;"/>
                                    </div>
                                    <div class="carousel-item">
                                        <img class="d-block w-100" alt="Image descriptive" src="{{ asset('storage/Image_Cas/'. $cas->image4) }}" style="width: 100%; object-fit: cover;"/>
                                    </div>
                                </div>
                                <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Précédent</span>
                                </a>
                                <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Suivant</span>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-2"></div>
				    </div>
                </div>
			</div>
		</div>
	</div>
</div>

@endsection